package com.coreguard.android.data.local.dao

import com.coreguard.android.data.local.entity.QuillaHypothesisEntity

/**
 * Data-access object for [QuillaHypothesisEntity] records.
 *
 * Implementations are responsible for persisting hypotheses generated by
 * [com.quilla.intelligence.sdk.engine.SlidingWindowCorrelationEngine].
 */
interface QuillaLearningDao {

    /**
     * Inserts or replaces the given [entity], keyed by its id field.
     */
    fun upsertHypothesis(entity: QuillaHypothesisEntity)
}
