package com.coldboar.coreguard.quilla

/**
 * Network telemetry event emitted by Network Shield for a single observed
 * outbound connection from a monitored package.
 */
data class NetworkEvent(
    val packageName: String,
    val destinationDomainOrIp: String,
    val isUntrustedNetwork: Boolean,
    val bytesTransferred: Long
)

/**
 * Runtime Application Self-Protection (RASP) telemetry event capturing
 * behavioural signals for a monitored package.
 */
data class RaspEvent(
    val packageName: String,
    val isDynamicCodeLoaded: Boolean,
    val isRootDetected: Boolean,
    val modifiedFilePath: String? = null
)

/**
 * A parsed Amnesty International STIX2 indicator of compromise.
 *
 * @param id            STIX2 object id (e.g. "indicator--...").
 * @param indicatorType Normalised type string: "DOMAIN", "IP", "HASH", or "GENERIC".
 * @param patternValue  The extracted indicator value (domain name, IP, hash, etc.).
 * @param description   Human-readable description from the STIX2 bundle.
 */
data class AmnestyIndicator(
    val id: String,
    val indicatorType: String,
    val patternValue: String,
    val description: String
)

/**
 * A correlated hypothesis that a package is exhibiting malicious behaviour.
 *
 * Generated by [QuillaCorrelationEngine] when the combined confidence score
 * for a set of signals crosses [QuillaCorrelationEngine.ACTIVATION_THRESHOLD].
 *
 * @param id             UUID assigned at creation time.
 * @param hypothesisType Classifier string (e.g. "AMNESTY_IOC_BEHAVIORAL_MATCH").
 * @param summary        Human-readable summary sentence.
 * @param evidenceJson   JSON blob containing packageName, confidence, reasons array,
 *                       and bytesTransferred.
 * @param confidence     Combined confidence score, clamped to [0.0, 1.0].
 * @param status         Lifecycle status; "ACTIVE" when first created.
 */
data class QuillaHypothesis(
    val id: String,
    val hypothesisType: String,
    val summary: String,
    val evidenceJson: String,
    val confidence: Float,
    val status: String
)
