package com.coldboar.coreguard.quilla

/**
 * Network telemetry event emitted by Network Shield for a single observed
 * outbound connection from a monitored package.
 */
data class NetworkEvent(
    val packageName: String,
    val destinationDomainOrIp: String,
    val isUntrustedNetwork: Boolean,
    val bytesTransferred: Long
)

/**
 * Runtime Application Self-Protection (RASP) telemetry event capturing
 * behavioral signals for a monitored package.
 */
data class RaspEvent(
    val packageName: String,
    val isDynamicCodeLoaded: Boolean,
    val isRootDetected: Boolean,
    val modifiedFilePath: String? = null
)

/**
 * A parsed Amnesty International STIX2 indicator of compromise.
 *
 * @param id            STIX2 object id (e.g. "indicator--...").
 * @param indicatorType Normalised type string: "DOMAIN", "IP", "HASH", or "GENERIC".
 * @param patternValue  The extracted indicator value (domain name, IP, hash, etc.).
 * @param description   Human-readable description from the STIX2 bundle.
 */
data class AmnestyIndicator(
    val id: String,
    val indicatorType: String,
    val patternValue: String,
    val description: String
)

/**
 * A parsed multi-source STIX 2.1 threat indicator with source attribution and TTL decay.
 *
 * @param id            STIX2 object id (e.g. "indicator--...").
 * @param sourceFeed    Human-readable feed label (e.g. "Amnesty International", "CISA KEV").
 * @param indicatorType Normalised type string: "DOMAIN", "IP", "HASH", or "GENERIC".
 * @param patternValue  The extracted indicator value (domain name, IP, hash, etc.).
 * @param description   Human-readable description from the STIX2 bundle.
 * @param ttlTimestamp  Absolute epoch-ms timestamp after which this indicator should be
 *                      considered expired (rule-decay support).
 */
data class StixIndicator(
    val id: String,
    val sourceFeed: String,
    val indicatorType: String,
    val patternValue: String,
    val description: String,
    val ttlTimestamp: Long
)

/**
 * Structured evidence payload capturing all correlated signals for a package at a point in time.
 *
 * Serialised to JSON and stored inside [QuillaHypothesis.evidenceJson].
 *
 * @param packageName      Observed Android package under analysis.
 * @param matchedIoc       The STIX indicator value that triggered the match, or null.
 * @param iocSource        Feed label of the matched indicator (e.g. "Amnesty International").
 * @param raspSignals      List of RASP signal descriptions active during the correlation window.
 * @param bytesTransferred Total bytes transferred by the package in the correlation window.
 * @param untrustedNetwork True if the package was observed on an untrusted network.
 * @param timestamp        Epoch-ms creation time; defaults to [System.currentTimeMillis].
 */
data class EvidencePayload(
    val packageName: String,
    val matchedIoc: String? = null,
    val iocSource: String? = null,
    val raspSignals: List<String> = emptyList(),
    val bytesTransferred: Long = 0L,
    val untrustedNetwork: Boolean = false,
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * A raw device telemetry event ingested by [SlidingWindowCorrelationEngine].
 *
 * @param packageName Observed Android package that produced the event.
 * @param type        Event classifier: "RASP_DCL", "RASP_ROOT", "NETWORK_OUTBOUND",
 *                    or "NETWORK_UNTRUSTED".
 * @param detail      Type-dependent payload string (destination domain/IP, file path, etc.).
 * @param timestamp   Epoch-ms event creation time; defaults to [System.currentTimeMillis].
 */
data class RawEvent(
    val packageName: String,
    val type: String,
    val detail: String,
    val timestamp: Long = System.currentTimeMillis()
)

/**
 * A correlated hypothesis that a package is exhibiting malicious behaviour.
 *
 * Generated by [QuillaCorrelationEngine] when the combined confidence score
 * for a set of signals crosses [QuillaCorrelationEngine.ACTIVATION_THRESHOLD].
 *
 * @param id             UUID assigned at creation time.
 * @param hypothesisType Classifier string (e.g. "AMNESTY_IOC_BEHAVIORAL_MATCH").
 * @param summary        Human-readable summary sentence.
 * @param evidenceJson   JSON blob containing packageName, confidence, reasons array,
 *                       and bytesTransferred.
 * @param confidence     Combined confidence score, clamped to [0.0, 1.0].
 * @param status         Lifecycle status; "ACTIVE" when first created.
 */
data class QuillaHypothesis(
    val id: String,
    val hypothesisType: String,
    val summary: String,
    val evidenceJson: String,
    val confidence: Float,
    val status: String
)
