package com.coreguard.android.data.local

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import com.coreguard.android.data.local.dao.QuillaLearningDao
import com.coreguard.android.data.local.dao.ScanSessionDao
import com.coreguard.android.data.local.entity.FindingEntity
import com.coreguard.android.data.local.entity.FindingEvidenceEntity
import com.coreguard.android.data.local.entity.QuillaHypothesisEntity
import com.coreguard.android.data.local.entity.ScanSessionEntity
import com.coreguard.android.data.local.entity.ScanStageEventEntity
import com.coreguard.android.data.local.entity.ThreatIntelReferenceEntity

/**
 * Room database that persists threat hypotheses generated by Quilla Intelligence.
 *
 * Access the singleton instance via [QuillaDatabase.getInstance]. The database
 * file is named `quilla_intelligence.db` and stored in the app's private storage.
 *
 * Schema version history:
 * - Version 1: initial schema with the [QuillaHypothesisEntity] table.
 * - Version 2: durable scan-session evidence tables and timeline stage events.
 */
@Database(
    entities = [
        QuillaHypothesisEntity::class,
        ScanSessionEntity::class,
        FindingEntity::class,
        FindingEvidenceEntity::class,
        ScanStageEventEntity::class,
        ThreatIntelReferenceEntity::class
    ],
    version = 2,
    exportSchema = false
)
abstract class QuillaDatabase : RoomDatabase() {

    /** Returns the DAO for reading and writing [QuillaHypothesisEntity] records. */
    abstract fun quillaLearningDao(): QuillaLearningDao
    abstract fun scanSessionDao(): ScanSessionDao

    companion object {
        private const val DB_NAME = "quilla_intelligence.db"

        @Volatile
        private var instance: QuillaDatabase? = null

        private val MIGRATION_1_2 = object : Migration(1, 2) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `scan_sessions` (
                        `sessionId` TEXT NOT NULL,
                        `status` TEXT NOT NULL,
                        `startedAtMs` INTEGER NOT NULL,
                        `endedAtMs` INTEGER NOT NULL,
                        `failureReason` TEXT,
                        `scannerEngineVersion` TEXT NOT NULL,
                        `schemaVersion` INTEGER NOT NULL,
                        `observedFindings` INTEGER NOT NULL,
                        `inferredFindings` INTEGER NOT NULL,
                        `unavailableFindings` INTEGER NOT NULL,
                        `deepInspectionEnabled` INTEGER NOT NULL,
                        `feedSource` TEXT NOT NULL,
                        `feedVersion` TEXT,
                        `feedAuthenticity` TEXT NOT NULL,
                        `feedLoadedAtMs` INTEGER NOT NULL,
                        PRIMARY KEY(`sessionId`)
                    )
                    """.trimIndent()
                )
                db.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `findings` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `sessionId` TEXT NOT NULL,
                        `findingId` TEXT NOT NULL,
                        `title` TEXT NOT NULL,
                        `severity` TEXT NOT NULL,
                        `confidence` TEXT NOT NULL,
                        `evidenceClass` TEXT NOT NULL,
                        `affectedComponent` TEXT NOT NULL,
                        `source` TEXT NOT NULL,
                        `verificationState` TEXT NOT NULL,
                        FOREIGN KEY(`sessionId`) REFERENCES `scan_sessions`(`sessionId`) ON UPDATE NO ACTION ON DELETE CASCADE
                    )
                    """.trimIndent()
                )
                db.execSQL("CREATE INDEX IF NOT EXISTS `index_findings_sessionId` ON `findings` (`sessionId`)")
                db.execSQL("CREATE INDEX IF NOT EXISTS `index_findings_findingId` ON `findings` (`findingId`)")
                db.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `finding_evidence` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `findingRowId` INTEGER NOT NULL,
                        `evidenceType` TEXT NOT NULL,
                        `evidenceValue` TEXT NOT NULL,
                        `independentSource` INTEGER NOT NULL,
                        FOREIGN KEY(`findingRowId`) REFERENCES `findings`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE
                    )
                    """.trimIndent()
                )
                db.execSQL("CREATE INDEX IF NOT EXISTS `index_finding_evidence_findingRowId` ON `finding_evidence` (`findingRowId`)")
                db.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `scan_stage_events` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `sessionId` TEXT NOT NULL,
                        `stageId` TEXT NOT NULL,
                        `label` TEXT NOT NULL,
                        `completedUnits` INTEGER,
                        `totalUnits` INTEGER,
                        `timestampMs` INTEGER NOT NULL,
                        `visibilityLimitation` TEXT,
                        FOREIGN KEY(`sessionId`) REFERENCES `scan_sessions`(`sessionId`) ON UPDATE NO ACTION ON DELETE CASCADE
                    )
                    """.trimIndent()
                )
                db.execSQL("CREATE INDEX IF NOT EXISTS `index_scan_stage_events_sessionId` ON `scan_stage_events` (`sessionId`)")
                db.execSQL("CREATE INDEX IF NOT EXISTS `index_scan_stage_events_stageId` ON `scan_stage_events` (`stageId`)")
                db.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `threat_intel_references` (
                        `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                        `sessionId` TEXT NOT NULL,
                        `findingRowId` INTEGER,
                        `reference` TEXT NOT NULL,
                        `feedSource` TEXT NOT NULL,
                        `feedVersion` TEXT,
                        FOREIGN KEY(`sessionId`) REFERENCES `scan_sessions`(`sessionId`) ON UPDATE NO ACTION ON DELETE CASCADE,
                        FOREIGN KEY(`findingRowId`) REFERENCES `findings`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE
                    )
                    """.trimIndent()
                )
                db.execSQL("CREATE INDEX IF NOT EXISTS `index_threat_intel_references_sessionId` ON `threat_intel_references` (`sessionId`)")
                db.execSQL("CREATE INDEX IF NOT EXISTS `index_threat_intel_references_findingRowId` ON `threat_intel_references` (`findingRowId`)")
            }
        }

        fun getInstance(context: Context): QuillaDatabase =
            // Double-checked locking: the outer elvis is the fast-path read (no lock);
            // the inner elvis inside synchronized is the authoritative second check that
            // prevents two threads that both passed the outer check from each building
            // a separate instance. @Volatile on `instance` guarantees write visibility.
            instance ?: synchronized(this) {
                instance ?: Room.databaseBuilder(
                    context.applicationContext,
                    QuillaDatabase::class.java,
                    DB_NAME
                )
                    .addMigrations(MIGRATION_1_2)
                    .build()
                    .also { instance = it }
            }
    }
}
