package com.coreguard.android.data.local

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import com.coreguard.android.data.local.dao.QuillaLearningDao
import com.coreguard.android.data.local.entity.QuillaHypothesisEntity

/**
 * Room database that persists threat hypotheses generated by Quilla Intelligence.
 *
 * Access the singleton instance via [QuillaDatabase.getInstance]. The database
 * file is named `quilla_intelligence.db` and stored in the app's private storage.
 *
 * Schema version history:
 * - Version 1: initial schema with the [QuillaHypothesisEntity] table.
 */
@Database(
    entities = [QuillaHypothesisEntity::class],
    version = 1,
    exportSchema = false
)
abstract class QuillaDatabase : RoomDatabase() {

    /** Returns the DAO for reading and writing [QuillaHypothesisEntity] records. */
    abstract fun quillaLearningDao(): QuillaLearningDao

    companion object {
        private const val DB_NAME = "quilla_intelligence.db"

        @Volatile
        private var instance: QuillaDatabase? = null

        /**
         * Returns the singleton [QuillaDatabase], creating it on first access.
         *
         * [fallbackToDestructiveMigration] is set so that any future schema version bump
         * that lacks an explicit migration path drops and recreates the database instead of
         * crashing. Because the threat-hypothesis data is ephemeral and can be regenerated
         * by re-running the correlation engine, data loss on migration is acceptable.
         *
         * @param context Any [Context]; the application context is used internally
         *   to avoid retaining Activity references across the process lifetime.
         */
        fun getInstance(context: Context): QuillaDatabase =
            // Double-checked locking: the outer elvis is the fast-path read (no lock);
            // the inner elvis inside synchronized is the authoritative second check that
            // prevents two threads that both passed the outer check from each building
            // a separate instance. @Volatile on `instance` guarantees write visibility.
            instance ?: synchronized(this) {
                instance ?: Room.databaseBuilder(
                    context.applicationContext,
                    QuillaDatabase::class.java,
                    DB_NAME
                )
                    .fallbackToDestructiveMigration()
                    .build()
                    .also { instance = it }
            }
    }
}
