package com.coreguard.android.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Persistent record of a threat hypothesis generated by the
 * [com.quilla.intelligence.sdk.engine.SlidingWindowCorrelationEngine].
 *
 * @param id             Auto-generated primary key assigned by Room on insert.
 * @param hypothesisType Classifier string, e.g. "BEHAVIORAL_ANOMALY" or "STIX_THREAT_MATCH".
 * @param confidence     Combined confidence score in [0.0, 1.0].
 * @param summary        Human-readable description including the affected package name.
 * @param evidenceJson   JSON blob containing supporting evidence details.
 */
@Entity(tableName = "quilla_hypotheses")
data class QuillaHypothesisEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val hypothesisType: String,
    val confidence: Float,
    val summary: String,
    val evidenceJson: String
)
