package com.coreguard.android.data.local.entity

/**
 * Persistent record of a threat hypothesis generated by the
 * [com.quilla.intelligence.sdk.engine.SlidingWindowCorrelationEngine].
 *
 * @param hypothesisType Classifier string, e.g. "BEHAVIORAL_ANOMALY" or "STIX_THREAT_MATCH".
 * @param confidence     Combined confidence score in [0.0, 1.0].
 * @param summary        Human-readable description including the affected package name.
 * @param evidenceJson   JSON blob containing supporting evidence details.
 */
data class QuillaHypothesisEntity(
    val hypothesisType: String,
    val confidence: Float,
    val summary: String,
    val evidenceJson: String
)
