package com.coldboar.coreguard

import android.content.Context
import android.content.pm.PackageManager
import android.content.pm.Signature
import android.os.Build
import com.coldboar.coreguard.defense.AccessibilityAbuseEvaluator
import com.coldboar.coreguard.defense.OverlayAbuseEvaluator
import com.coldboar.coreguard.defense.SideloadRiskEvaluator
import java.security.MessageDigest
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.coroutineScope
// BuildConfig.EXPECTED_CERT_SHA256 is generated by gradle/android-app.gradle

/**
 * Builds and runs the standard set of security check evaluators.
 *
 * Shared by [MainActivity] (Guardian Score preview) and
 * the Compliance / Home Compose screens (full per-check breakdown) so both are
 * always driven by the same evaluator configuration.
 *
 * Includes Sandalphon-grounded intrusion surface checks (overlay / Accessibility /
 * sideload) for Trojan and unauthorized red-team style abuse.
 */
object SecurityCheckRunner {

    /**
     * Runs all evaluators sequentially on the calling thread.
     *
     * Prefer [runConcurrent] from coroutine contexts — it dispatches each
     * evaluator concurrently on [Dispatchers.IO], cutting wall-clock time from
     * the sum of all evaluator durations to roughly the slowest single evaluator.
     */
    fun run(context: Context): List<SecurityCheckResult> =
        evaluators(context).map { it.evaluate() }

    /**
     * Runs all evaluators concurrently on [Dispatchers.IO] and awaits all results.
     *
     * Each evaluator is independent and thread-safe (injectable lambdas, no shared
     * mutable state), so dispatching them in parallel is safe. On a quad-core device
     * this typically reduces wall-clock time by 3–5× compared to [run].
     *
     * Must be called from a coroutine context. Exceptions in any single evaluator
     * are propagated via [coroutineScope] and cancel the remaining work.
     */
    suspend fun runConcurrent(context: Context): List<SecurityCheckResult> = coroutineScope {
        evaluators(context)
            .map { evaluator -> async(Dispatchers.IO) { evaluator.evaluate() } }
            .awaitAll()
    }

    fun evaluators(context: Context): List<SecurityCheckEvaluator> {
        val keyLevel = { CoreGuardApplication.get()?.keyManager?.securityLevel ?: KeySecurityLevel.SOFTWARE }
        return listOf(
            DebuggerCheckEvaluator(),
            NativeDebuggerEvaluator(),
            FridaDetectionEvaluator(),
            HookDetectionEvaluator(),
            MemoryIntegrityEvaluator(),
            EmulatorCheckEvaluator(),
            RootCheckEvaluator(),
            MountIntegrityEvaluator(),
            BuildTypeCheckEvaluator(),
            SignatureCheckEvaluator(
                actualSha256 = { certSha256(context) },
                expectedSha256 = BuildConfig.EXPECTED_CERT_SHA256
            ),
            StrongBoxCheckEvaluator(level = keyLevel),
            ProcessLineageEvaluator(),
            SpywareScanEvaluator(),
            OverlayAbuseEvaluator(context),
            AccessibilityAbuseEvaluator(context),
            SideloadRiskEvaluator(context)
        )
    }

    /**
     * Returns the SHA-256 fingerprint of the first signing certificate, or
     * empty string on failure.
     */
    fun certSha256(context: Context): String {
        return try {
            val packageManager = context.packageManager
            val packageName = context.packageName
            @Suppress("DEPRECATION")
            val sig: Signature = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                packageManager.getPackageInfo(packageName, PackageManager.GET_SIGNING_CERTIFICATES)
                    .signingInfo?.apkContentsSigners?.firstOrNull() ?: return ""
            } else {
                packageManager.getPackageInfo(packageName, PackageManager.GET_SIGNATURES)
                    .signatures?.firstOrNull() ?: return ""
            }
            val md = MessageDigest.getInstance("SHA-256")
            val digest = md.digest(sig.toByteArray())
            digest.joinToString(":") { "%02X".format(it) }
        } catch (_: Exception) {
            ""
        }
    }
}
